/**
 * Reservation System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookingSeries { 
    id: string;
    interval: BookingSeries.IntervalEnum;
    intervalCount: number;
    startDate: string;
    endDate: string | null;
    instantiatedUntil: string;
}
export namespace BookingSeries {
    export const IntervalEnum = {
        Daily: 'DAILY',
        Weekly: 'WEEKLY',
        Monthly: 'MONTHLY'
    } as const;
    export type IntervalEnum = typeof IntervalEnum[keyof typeof IntervalEnum];
}


