/**
 * Reservation System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RolePermissions { 
    /**
     * View bookings without name and contact details
     */
    viewBookings: boolean;
    /**
     * View bookings with name and contact details
     */
    viewBookingsDetails: boolean;
    /**
     * Create bookings
     */
    createBookings?: boolean;
    /**
     * Ignore time-based booking restrictions when creating or managing bookings
     */
    noTimeRestrictions?: boolean;
    /**
     * Manage bookings
     */
    manageBookings: boolean;
    /**
     * Manage workplaces
     */
    manageWorkplaces: boolean;
    /**
     * Manage areas
     */
    manageAreas: boolean;
    /**
     * Manage user roles
     */
    manageRoles: boolean;
}

