/**
 * Reservation System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RolePermissions } from './rolePermissions';


export interface Role { 
    name: string;
    passwordHash?: string;
    permissions: RolePermissions;
}

