<?php declare(strict_types=1);

/**
 * Reservation System API
 * API for managing areas, workplaces, bookings, booking series, and roles.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


use Illuminate\Support\Facades\Route;

/**
 * GET areasGet
 * Summary: List areas
 * Notes: 
 */
Route::GET('/areas', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'areasGet'])->name('default.areas.get');

/**
 * DELETE areasIdDelete
 * Summary: Delete area
 * Notes: 
 */
Route::DELETE('/areas/{id}', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'areasIdDelete'])->name('default.areas.id.delete');

/**
 * PUT areasIdPut
 * Summary: Update area
 * Notes: 
 */
Route::PUT('/areas/{id}', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'areasIdPut'])->name('default.areas.id.put');

/**
 * POST areasPost
 * Summary: Create area
 * Notes: 
 */
Route::POST('/areas', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'areasPost'])->name('default.areas.post');

/**
 * GET bookingSeriesGet
 * Summary: List booking series
 * Notes: 
 */
Route::GET('/booking-series', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'bookingSeriesGet'])->name('default.booking.series.get');

/**
 * DELETE bookingSeriesIdDelete
 * Summary: Delete booking series
 * Notes: 
 */
Route::DELETE('/booking-series/{id}', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'bookingSeriesIdDelete'])->name('default.booking.series.id.delete');

/**
 * PUT bookingSeriesIdPut
 * Summary: Update booking series
 * Notes: 
 */
Route::PUT('/booking-series/{id}', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'bookingSeriesIdPut'])->name('default.booking.series.id.put');

/**
 * POST bookingSeriesPost
 * Summary: Create booking series
 * Notes: 
 */
Route::POST('/booking-series', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'bookingSeriesPost'])->name('default.booking.series.post');

/**
 * GET bookingsGet
 * Summary: List bookings
 * Notes: 
 */
Route::GET('/bookings', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'bookingsGet'])->name('default.bookings.get');

/**
 * DELETE bookingsIdDelete
 * Summary: Delete booking
 * Notes: 
 */
Route::DELETE('/bookings/{id}', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'bookingsIdDelete'])->name('default.bookings.id.delete');

/**
 * GET bookingsIdGet
 * Summary: Get booking details
 * Notes: 
 */
Route::GET('/bookings/{id}', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'bookingsIdGet'])->name('default.bookings.id.get');

/**
 * PUT bookingsIdPut
 * Summary: Update booking
 * Notes: 
 */
Route::PUT('/bookings/{id}', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'bookingsIdPut'])->name('default.bookings.id.put');

/**
 * POST bookingsPost
 * Summary: Create booking
 * Notes: 
 */
Route::POST('/bookings', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'bookingsPost'])->name('default.bookings.post');

/**
 * GET rolesGet
 * Summary: List roles
 * Notes: 
 */
Route::GET('/roles', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'rolesGet'])->name('default.roles.get');

/**
 * DELETE rolesNameDelete
 * Summary: Delete role
 * Notes: 
 */
Route::DELETE('/roles/{name}', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'rolesNameDelete'])->name('default.roles.name.delete');

/**
 * PUT rolesNamePut
 * Summary: Update role
 * Notes: 
 */
Route::PUT('/roles/{name}', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'rolesNamePut'])->name('default.roles.name.put');

/**
 * POST rolesPost
 * Summary: Create role
 * Notes: 
 */
Route::POST('/roles', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'rolesPost'])->name('default.roles.post');

/**
 * GET workplacesGet
 * Summary: List workplaces
 * Notes: 
 */
Route::GET('/workplaces', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'workplacesGet'])->name('default.workplaces.get');

/**
 * DELETE workplacesIdDelete
 * Summary: Delete workplace
 * Notes: 
 */
Route::DELETE('/workplaces/{id}', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'workplacesIdDelete'])->name('default.workplaces.id.delete');

/**
 * PUT workplacesIdPut
 * Summary: Update workplace
 * Notes: 
 */
Route::PUT('/workplaces/{id}', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'workplacesIdPut'])->name('default.workplaces.id.put');

/**
 * POST workplacesPost
 * Summary: Create workplace
 * Notes: 
 */
Route::POST('/workplaces', [\OpenAPI\Server\Http\Controllers\DefaultController::class, 'workplacesPost'])->name('default.workplaces.post');

