/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Area {
  /**
   * Bookings in this area may span the night. Start and end still have to fall within
   * opening hours; only the hours in between may lie outside.
   */
  allowNightlyActivities: boolean;

  /**
   * Any CSS colour the browser understands, used as-is as the background of this area's
   * blocks. The seeded areas use `oklch(0.8 0.1 <hue>)` so that they differ in hue alone
   * and share a lightness — a hex value works just as well.
   */
  color: string;
  id: string;
  maxBookingDurationMinutes: number;

  /**
   * Overrides the global value when set.
   */
  maxBookingEndOffsetDays: number | null;
  name: string;

  /**
   * Set through PUT /areas/order, not here.
   */
  sortOrder: number;
}
