/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Without sortOrder: the order is set for all areas at once through PUT /areas/order.
 * A new area lands at the end.
 */
export interface AreaWrite {
  allowNightlyActivities: boolean;
  color: string;
  maxBookingDurationMinutes: number;
  maxBookingEndOffsetDays?: number | null;
  name: string;
}
