/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AreaWrite {
  allowNightlyActivities: boolean;
  color: string;
  maxBookingDurationMinutes: number;
  maxBookingEndOffsetDays?: number | null;
  name: string;
  sortOrder?: number;
}
