/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Area {
  /**
   * Bookings in this area may span the night. Start and end still have to fall within
   * opening hours; only the hours in between may lie outside.
   */
  allowNightlyActivities: boolean;
  color: string;
  id: string;
  maxBookingDurationMinutes: number;

  /**
   * Overrides the global value when set.
   */
  maxBookingEndOffsetDays: number | null;
  name: string;
  sortOrder: number;
}
