/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Start and end must sit on the 15-minute grid and fall within opening hours. Unless the area
 * allows nightly activities, both must be on the same day.
 */
export interface BookingWrite {
  contact: string;
  endTime: string;
  name: string;

  /**
   * When true the booking occupies only workplaceId itself: the workplaces it would
   * otherwise block (via blocksWorkplaceIds or blocksWorkplacesWithTag) stay free and
   * blockedWorkplaceIds is recorded empty. Bookings that block this workplace still
   * collide. Omitted on update means unchanged, not revoked. Defaults to false.
   */
  skipAutomaticBlocking?: boolean;
  startTime: string;

  /**
   * Must be true when the workplace has usageRules.
   */
  usageRulesAcknowledged?: boolean;
  workplaceId: string;
}
