/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookingSeriesWrite {
  contact: string;
  endDate?: string | null;
  firstInstanceEnd: string;
  firstInstanceStart: string;
  interval: 'WEEKLY' | 'MONTHLY';
  intervalCount: number;
  name: string;
  workplaceId: string;
}
