/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Booking {
  /**
   * Server-computed snapshot taken when the booking was created or last changed: the union of
   * the workplace's blocksWorkplaceIds and every workplace that carried a matching tag at that
   * moment. Never accepted from a client. Drives the grey blocks in the calendar.
   */
  blockedWorkplaceIds: Array<string>;
  bookingSeriesId: string | null;

  /**
   * Time inside opening hours only — night hours of an over-night booking are not counted.
   * Derived from startTime and endTime; validated against the maximum booking duration.
   */
  chargeableDurationMinutes: number;

  /**
   * Only present with viewBookingsDetails; null otherwise.
   */
  contact: string | null;
  createdAt: string;

  /**
   * Null for bookings the system created itself — series instances have no
   * creator. Kept as a dangling reference when the role is later deleted.
   */
  creatorRoleId: string | null;
  endTime: string;
  id: string;

  /**
   * Only present with manageRoles; null otherwise. Cleared 90 days after creation.
   */
  ipAddress?: string | null;

  /**
   * Who booked. Always present — reaching this endpoint at all already requires
   * viewBookings.
   */
  name: string;

  /**
   * Set once someone edits a series instance by hand. Editing the series then leaves this
   * booking alone instead of regenerating it. Always false when bookingSeriesId is null.
   */
  seriesDetached: boolean;
  startTime: string;
  usageRulesAcknowledged: boolean;
  workplaceId: string;
}
