/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookingSeries {
  contact: string;

  /**
   * Last day the series may produce instances. Open-ended when null.
   */
  endDate: string | null;

  /**
   * Local wall-clock time, same rules as firstInstanceStart.
   */
  firstInstanceEnd: string;

  /**
   * Local wall-clock time in the configured timezone, deliberately without a UTC offset, so a
   * recurring 09:00 stays 09:00 across DST changes. MONTHLY repeats on the same day of month;
   * months lacking that day are skipped.
   */
  firstInstanceStart: string;
  id: string;

  /**
   * How far instances have been generated. Advanced to today + 1 year by the daily job.
   */
  instantiatedUntil: string;
  interval: 'DAILY' | 'WEEKLY' | 'MONTHLY';

  /**
   * e.g. 2 with WEEKLY means every second week.
   */
  intervalCount: number;
  name: string;
  workplaceId: string;
}
