/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Start and end must sit on the 15-minute grid and fall within opening hours. Unless the area
 * allows nightly activities, both must be on the same day.
 */
export interface BookingWrite {
  contact: string;
  endTime: string;
  name: string;
  startTime: string;

  /**
   * Must be true when the workplace has usageRules.
   */
  usageRulesAcknowledged?: boolean;
  workplaceId: string;
}
