/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Result of the pre-flight check backing the real-time collision hint in the form.
 */
export interface BookingValidation {
  chargeableDurationMinutes?: number;
  conflictingBookingIds: Array<string>;
  valid: boolean;
  violations: Array<{
'code': 'COLLISION' | 'OUTSIDE_OPENING_HOURS' | 'EXCEEDS_MAX_DURATION' | 'EXCEEDS_MAX_END_OFFSET' | 'STARTS_IN_PAST' | 'NOT_ON_GRID' | 'SPANS_NIGHT_NOT_ALLOWED' | 'WORKPLACE_NOT_BOOKABLE' | 'USAGE_RULES_NOT_ACKNOWLEDGED';
'message': string;
}>;
}
