/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Error } from '../models/error';
export type BookingConflictError = Error & {

/**
 * Existing bookings the request collides with.
 */
'conflictingBookingIds': Array<string>;
};

