/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Global configuration. Readable by everyone, writable with manageRoles.
 */
export interface Config {

  /**
   * Local time, aligned to the 15-minute grid. Must be later than opensAt.
   */
  closesAt: string;

  /**
   * Default limit on how far ahead a booking may end. Areas may override it.
   */
  maxBookingEndOffsetDays: number;

  /**
   * Local time, aligned to the 15-minute grid. Valid on all weekdays.
   */
  opensAt: string;

  /**
   * IANA name. Used for display and for interpreting booking series wall-clock times.
   */
  timezone: string;
}
