/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Error {
  /**
   * Field-level validation messages, keyed by field path.
   */
  errors?: {
    [key: string]: Array<string>;
  };
  message: string;
}
