/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Where the overview map fetches its drawing. Either the file shipped with the interface or
 * one uploaded afterwards — the client follows `url` and needs to know nothing further.
 */
export interface FloorPlan {
  /**
   * True while nothing has been uploaded; `url` then points at the file that came with the
   * interface. A fresh installation therefore has a plan without anyone uploading one.
   */
  isDefault: boolean;

  /**
   * When the uploaded plan was stored. Null for the shipped one.
   */
  updatedAt: string | null;

  /**
   * Relative, like every URL this API hands out: API, storage and SPA live on the same host,
   * and an absolute one built from a misconfigured APP_URL would take the map down with it.
   */
  url: string;
}
