/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Permissions {
  /**
   * Manage areas
   */
  manageAreas: boolean;

  /**
   * Manage booking series
   */
  manageBookingSeries: boolean;

  /**
   * Create, update and delete any booking
   */
  manageBookings: boolean;

  /**
   * Manage user roles and global configuration
   */
  manageRoles: boolean;

  /**
   * Manage workplaces
   */
  manageWorkplaces: boolean;

  /**
   * Ignore maximum booking duration and maxBookingEndOffsetDays. Opening hours still apply.
   */
  noTimeRestrictions: boolean;

  /**
   * View bookings, including who booked. Contact details stay hidden.
   */
  viewBookings: boolean;

  /**
   * Additionally view the booker's contact details
   */
  viewBookingsDetails: boolean;
}
