/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Permissions } from '../models/permissions';

/**
 * The password is write-only and never returned. Hashing happens server-side; clients never
 * send or receive a hash. Omit `password` on update to leave it unchanged. The anonymous role
 * rejects any password.
 */
export interface RoleWrite {
  name: string;
  password?: string | null;
  permissions: Permissions;
}
