/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Permissions } from '../models/permissions';
export interface Role {
  /**
   * Stable and immutable. Referenced by Booking.creatorRoleId.
   */
  id: string;

  /**
   * Exactly one role carries this flag. It has no password, cannot be deleted, and is the
   * implicit role of unauthenticated clients. Not settable through the API.
   */
  isAnonymous: boolean;
  name: string;
  permissions: Permissions;
}
