/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * The ids in the order they are to have. Position 0 comes first. The list has to name every
 * entry exactly once — a partial one would leave the omitted rows at numbers that mean
 * nothing next to the new ones.
 */
export interface SortOrderWrite {
  ids: Array<string>;
}
