/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Workplace {
  areaId: string;
  blocksWorkplaceIds: Array<string>;
  blocksWorkplacesWithTag: Array<string>;

  /**
   * Markdown. Rendered against a safe subset — no HTML, no scripts, no external images.
   */
  description?: string | null;

  /**
   * Client-assigned, stable, URL- and SVG-safe (e.g. "tisch-4"). The overview map matches
   * SVG element ids against this value.
   */
  id: string;
  location?: string | null;

  /**
   * Overrides the area's value when set.
   */
  maxBookingDurationMinutes?: number | null;
  name: string;
  photoThumbnailUrl?: string | null;

  /**
   * Relative to the host that serves the API (`/storage/...`). Deliberately not absolute:
   * the API, the storage directory and the SPA live on the same host, and an absolute URL
   * built from a misconfigured APP_URL would break every photo at once.
   */
  photoUrl?: string | null;
  sortOrder: number;
  status: 'OK' | 'DEFECT' | 'DISABLED';

  /**
   * Stored without a leading "#", compared case-insensitively.
   */
  tags: Array<string>;

  /**
   * Markdown, same rendering restrictions. When set, bookings must acknowledge it.
   */
  usageRules?: string | null;
  wikiUrl?: string | null;
}
