/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkplaceCreate } from '../models/workplace-create';
export type WorkplaceUpdate = WorkplaceCreate & {
'id'?: any;
};

