/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Area } from './models/area';
export type { AreaWrite } from './models/area-write';
export type { Booking } from './models/booking';
export type { BookingConflictError } from './models/booking-conflict-error';
export type { BookingSeries } from './models/booking-series';
export type { BookingSeriesResult } from './models/booking-series-result';
export type { BookingSeriesWrite } from './models/booking-series-write';
export type { BookingValidation } from './models/booking-validation';
export type { BookingWrite } from './models/booking-write';
export type { Config } from './models/config';
export type { Error } from './models/error';
export type { LoginRequest } from './models/login-request';
export type { Permissions } from './models/permissions';
export type { Role } from './models/role';
export type { RoleWrite } from './models/role-write';
export type { Session } from './models/session';
export type { Workplace } from './models/workplace';
export type { WorkplaceCreate } from './models/workplace-create';
export type { WorkplaceUpdate } from './models/workplace-update';
