/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingSeries } from '../../models/booking-series';

export interface GetBookingSeries$Params {
  id: string;
}

export function getBookingSeries(
  http: HttpClient,
  rootUrl: string,
  params: GetBookingSeries$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<BookingSeries>> {
  const rb = new RequestBuilder(rootUrl, getBookingSeries.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingSeries>;
    }),
  );
}

getBookingSeries.PATH = '/booking-series/{id}';
