/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingSeries } from '../../models/booking-series';

export interface ListBookingSeries$Params {
}

export function listBookingSeries(http: HttpClient, rootUrl: string, params?: ListBookingSeries$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BookingSeries>>> {
  const rb = new RequestBuilder(rootUrl, listBookingSeries.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BookingSeries>>;
    })
  );
}

listBookingSeries.PATH = '/booking-series';
