/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingSeriesResult } from '../../models/booking-series-result';
import { BookingSeriesWrite } from '../../models/booking-series-write';

export interface UpdateBookingSeries$Params {
  id: string;
      body: BookingSeriesWrite
}

export function updateBookingSeries(http: HttpClient, rootUrl: string, params: UpdateBookingSeries$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingSeriesResult>> {
  const rb = new RequestBuilder(rootUrl, updateBookingSeries.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingSeriesResult>;
    })
  );
}

updateBookingSeries.PATH = '/booking-series/{id}';
