/**
 * Generates `src/app/shared/icon-paths.ts` from Lucide's original files.
 *
 * Why generated and not typed out: copying path data by hand works for a long
 * time and then fails silently — Lucide occasionally redraws icons, and a
 * rectangle shifted by one pixel goes unnoticed by everyone.
 *
 * Why not `lucide-angular`: its peer range ends at Angular 21. As a dev
 * dependency the question does not arise at all — only the generated table
 * reaches the bundle.
 *
 * Everything becomes a `<path>`: that keeps the component's template a single
 * loop rather than carrying a branch for each kind of element.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const iconsDir = resolve(here, '../node_modules/lucide-static/icons');
const target = resolve(here, '../src/app/shared/icon-paths.ts');

/**
 * Our names, on the left, say what for — Lucide's names, on the right, say what.
 * The mapping is the actual content of this file: `series` is called that here
 * because a recurring booking is meant, not `repeat`.
 */
const ICONS = {
  login: 'log-in',
  logout: 'log-out',
  back: 'chevron-left',
  forward: 'chevron-right',
  settings: 'settings',
  calendar: 'calendar',
  map: 'map',
  series: 'repeat',
  edit: 'pencil',
  add: 'plus',
  external: 'arrow-up-right',
  remove: 'x',
  drag: 'grip-vertical',
};

/** A number from an attribute, defaulting to 0 — Lucide omits `x`/`y` when they are 0. */
const num = (attrs, name, fallback = 0) => {
  const match = attrs.match(new RegExp(`\\b${name}="([^"]*)"`));
  return match ? Number(match[1]) : fallback;
};

const round = (n) => Number(n.toFixed(3));

/** A circle as two semicircular arcs — a single full arc would be degenerate. */
function circleToPath(attrs) {
  const cx = num(attrs, 'cx');
  const cy = num(attrs, 'cy');
  const r = num(attrs, 'r');
  return `M${round(cx - r)} ${cy}a${r} ${r} 0 1 0 ${r * 2} 0a${r} ${r} 0 1 0 ${-r * 2} 0`;
}

function rectToPath(attrs) {
  const x = num(attrs, 'x');
  const y = num(attrs, 'y');
  const w = num(attrs, 'width');
  const h = num(attrs, 'height');
  const rx = num(attrs, 'rx');
  const ry = num(attrs, 'ry', rx);

  if (!rx && !ry) {
    return `M${x} ${y}h${w}v${h}h${-w}z`;
  }

  const arc = (dx, dy) => `a${rx} ${ry} 0 0 1 ${round(dx)} ${round(dy)}`;

  return [
    `M${round(x + rx)} ${y}`,
    `h${round(w - 2 * rx)}`,
    arc(rx, ry),
    `v${round(h - 2 * ry)}`,
    arc(-rx, ry),
    `h${round(-(w - 2 * rx))}`,
    arc(-rx, -ry),
    `v${round(-(h - 2 * ry))}`,
    arc(rx, -ry),
    'z',
  ].join('');
}

const lineToPath = (attrs) =>
  `M${num(attrs, 'x1')} ${num(attrs, 'y1')}L${num(attrs, 'x2')} ${num(attrs, 'y2')}`;

function polylineToPath(attrs) {
  const points = attrs.match(/\bpoints="([^"]*)"/)?.[1] ?? '';
  const pairs = points.trim().split(/[\s,]+/);
  const steps = [];

  for (let i = 0; i < pairs.length; i += 2) {
    steps.push(`${i === 0 ? 'M' : 'L'}${pairs[i]} ${pairs[i + 1]}`);
  }

  return steps.join('');
}

function toPaths(svg) {
  const paths = [];

  for (const [, tag, attrs] of svg.matchAll(/<(path|circle|rect|line|polyline)\b([^>]*)>/g)) {
    if (tag === 'path') {
      paths.push(attrs.match(/\bd="([^"]*)"/)[1]);
    } else if (tag === 'circle') {
      paths.push(circleToPath(attrs));
    } else if (tag === 'rect') {
      paths.push(rectToPath(attrs));
    } else if (tag === 'line') {
      paths.push(lineToPath(attrs));
    } else {
      paths.push(polylineToPath(attrs));
    }
  }

  if (!paths.length) {
    throw new Error('No drawable elements found');
  }

  return paths;
}

const entries = Object.entries(ICONS).map(([name, lucideName]) => {
  const svg = readFileSync(resolve(iconsDir, `${lucideName}.svg`), 'utf8');
  const paths = toPaths(svg).map((d) => `    '${d}',`);
  return `  // ${lucideName}\n  ${name}: [\n${paths.join('\n')}\n  ],`;
});

const source = `// Generated by scripts/generate-icons.mjs — do not edit by hand.
// Source: lucide-static (ISC), 24×24 grid, stroke width 2, round caps.
// New icon: add it to the script, then run \`npm run icons:generate\`.

export type IconName =
${Object.keys(ICONS)
  .map((name) => `  | '${name}'`)
  .join('\n')};

export const ICON_PATHS: Record<IconName, readonly string[]> = {
${entries.join('\n')}
};
`;

writeFileSync(target, source);
console.log(`Wrote ${Object.keys(ICONS).length} icons to ${target}`);
