/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Workplace } from '../../models/workplace';

export interface GetWorkplace$Params {
  id: string;
}

export function getWorkplace(http: HttpClient, rootUrl: string, params: GetWorkplace$Params, context?: HttpContext): Observable<StrictHttpResponse<Workplace>> {
  const rb = new RequestBuilder(rootUrl, getWorkplace.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Workplace>;
    })
  );
}

getWorkplace.PATH = '/workplaces/{id}';
