/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Workplace } from '../../models/workplace';

export interface ListWorkplaces$Params {
  includeDisabled?: boolean;
  areaId?: string;
}

export function listWorkplaces(
  http: HttpClient,
  rootUrl: string,
  params?: ListWorkplaces$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<Workplace>>> {
  const rb = new RequestBuilder(rootUrl, listWorkplaces.PATH, 'get');
  if (params) {
    rb.query('includeDisabled', params.includeDisabled, {});
    rb.query('areaId', params.areaId, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Workplace>>;
    }),
  );
}

listWorkplaces.PATH = '/workplaces';
