/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Workplace } from '../../models/workplace';
import { WorkplaceUpdate } from '../../models/workplace-update';

export interface UpdateWorkplace$Params {
  id: string;
      body: WorkplaceUpdate
}

export function updateWorkplace(http: HttpClient, rootUrl: string, params: UpdateWorkplace$Params, context?: HttpContext): Observable<StrictHttpResponse<Workplace>> {
  const rb = new RequestBuilder(rootUrl, updateWorkplace.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Workplace>;
    })
  );
}

updateWorkplace.PATH = '/workplaces/{id}';
