/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Booking } from '../../models/booking';

export interface ListBookings$Params {
  from: string;
  to: string;
  workplaceId?: string;
  areaId?: string;
}

export function listBookings(http: HttpClient, rootUrl: string, params: ListBookings$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Booking>>> {
  const rb = new RequestBuilder(rootUrl, listBookings.PATH, 'get');
  if (params) {
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.query('workplaceId', params.workplaceId, {});
    rb.query('areaId', params.areaId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Booking>>;
    })
  );
}

listBookings.PATH = '/bookings';
