/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingValidation } from '../../models/booking-validation';
import { BookingWrite } from '../../models/booking-write';

export interface ValidateBooking$Params {
  /**
   * Set when checking an edit, so the booking does not collide with itself.
   */
  excludeBookingId?: string;
  body: BookingWrite;
}

export function validateBooking(
  http: HttpClient,
  rootUrl: string,
  params: ValidateBooking$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<BookingValidation>> {
  const rb = new RequestBuilder(rootUrl, validateBooking.PATH, 'post');
  if (params) {
    rb.query('excludeBookingId', params.excludeBookingId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingValidation>;
    }),
  );
}

validateBooking.PATH = '/bookings/validate';
