<?php declare(strict_types=1);

/**
 * Reservation System API
 * API for managing areas, workplaces, bookings, booking series, and roles.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Api;


interface DefaultApiInterface {


    /**
     * Operation areasGet
     *
     * List areas
     * @return \OpenAPI\Server\Model\Area[]
     */
    public function areasGet(
    ):
        array
    ;


    /**
     * Operation areasIdDelete
     *
     * Delete area
     * @param string $id
     * @return \OpenAPI\Server\Model\NoContent204
     */
    public function areasIdDelete(
            string $id,
    ):
        \OpenAPI\Server\Model\NoContent204
    ;


    /**
     * Operation areasIdPut
     *
     * Update area
     * @param string $id
     * @param \OpenAPI\Server\Model\Area $area
     * @return \OpenAPI\Server\Model\NoContent200
     */
    public function areasIdPut(
            string $id,
            \OpenAPI\Server\Model\Area $area,
    ):
        \OpenAPI\Server\Model\NoContent200
    ;


    /**
     * Operation areasPost
     *
     * Create area
     * @param \OpenAPI\Server\Model\Area $area
     * @return \OpenAPI\Server\Model\NoContent201
     */
    public function areasPost(
            \OpenAPI\Server\Model\Area $area,
    ):
        \OpenAPI\Server\Model\NoContent201
    ;


    /**
     * Operation bookingSeriesGet
     *
     * List booking series
     * @return \OpenAPI\Server\Model\BookingSeries[]
     */
    public function bookingSeriesGet(
    ):
        array
    ;


    /**
     * Operation bookingSeriesIdDelete
     *
     * Delete booking series
     * @param string $id
     * @return \OpenAPI\Server\Model\NoContent204
     */
    public function bookingSeriesIdDelete(
            string $id,
    ):
        \OpenAPI\Server\Model\NoContent204
    ;


    /**
     * Operation bookingSeriesIdPut
     *
     * Update booking series
     * @param string $id
     * @param \OpenAPI\Server\Model\BookingSeries $bookingSeries
     * @return \OpenAPI\Server\Model\NoContent200
     */
    public function bookingSeriesIdPut(
            string $id,
            \OpenAPI\Server\Model\BookingSeries $bookingSeries,
    ):
        \OpenAPI\Server\Model\NoContent200
    ;


    /**
     * Operation bookingSeriesPost
     *
     * Create booking series
     * @param \OpenAPI\Server\Model\BookingSeries $bookingSeries
     * @return \OpenAPI\Server\Model\NoContent201 | \OpenAPI\Server\Model\BookingSeriesPost200Response
     */
    public function bookingSeriesPost(
            \OpenAPI\Server\Model\BookingSeries $bookingSeries,
    ):
        \OpenAPI\Server\Model\NoContent201 | 
        \OpenAPI\Server\Model\BookingSeriesPost200Response
    ;


    /**
     * Operation bookingsGet
     *
     * List bookings
     * @param null | \DateTime $from
     * @param null | \DateTime $to
     * @param null | string $workplaceId
     * @return \OpenAPI\Server\Model\Booking[]
     */
    public function bookingsGet(
            ?\DateTime $from,
            ?\DateTime $to,
            ?string $workplaceId,
    ):
        array
    ;


    /**
     * Operation bookingsIdDelete
     *
     * Delete booking
     * @param string $id
     * @return \OpenAPI\Server\Model\NoContent204
     */
    public function bookingsIdDelete(
            string $id,
    ):
        \OpenAPI\Server\Model\NoContent204
    ;


    /**
     * Operation bookingsIdGet
     *
     * Get booking details
     * @param string $id
     * @return \OpenAPI\Server\Model\Booking
     */
    public function bookingsIdGet(
            string $id,
    ):
        \OpenAPI\Server\Model\Booking
    ;


    /**
     * Operation bookingsIdPut
     *
     * Update booking
     * @param string $id
     * @param \OpenAPI\Server\Model\Booking $booking
     * @return \OpenAPI\Server\Model\NoContent200 | \OpenAPI\Server\Model\Error
     */
    public function bookingsIdPut(
            string $id,
            \OpenAPI\Server\Model\Booking $booking,
    ):
        \OpenAPI\Server\Model\NoContent200 | 
        \OpenAPI\Server\Model\Error
    ;


    /**
     * Operation bookingsPost
     *
     * Create booking
     * @param \OpenAPI\Server\Model\Booking $booking
     * @return \OpenAPI\Server\Model\NoContent201 | \OpenAPI\Server\Model\Error
     */
    public function bookingsPost(
            \OpenAPI\Server\Model\Booking $booking,
    ):
        \OpenAPI\Server\Model\NoContent201 | 
        \OpenAPI\Server\Model\Error
    ;


    /**
     * Operation rolesGet
     *
     * List roles
     * @return \OpenAPI\Server\Model\Role[]
     */
    public function rolesGet(
    ):
        array
    ;


    /**
     * Operation rolesNameDelete
     *
     * Delete role
     * @param string $name
     * @return \OpenAPI\Server\Model\NoContent204
     */
    public function rolesNameDelete(
            string $name,
    ):
        \OpenAPI\Server\Model\NoContent204
    ;


    /**
     * Operation rolesNamePut
     *
     * Update role
     * @param string $name
     * @param \OpenAPI\Server\Model\Role $role
     * @return \OpenAPI\Server\Model\NoContent200
     */
    public function rolesNamePut(
            string $name,
            \OpenAPI\Server\Model\Role $role,
    ):
        \OpenAPI\Server\Model\NoContent200
    ;


    /**
     * Operation rolesPost
     *
     * Create role
     * @param \OpenAPI\Server\Model\Role $role
     * @return \OpenAPI\Server\Model\NoContent201
     */
    public function rolesPost(
            \OpenAPI\Server\Model\Role $role,
    ):
        \OpenAPI\Server\Model\NoContent201
    ;


    /**
     * Operation workplacesGet
     *
     * List workplaces
     * @param null | bool $includeDisabled
     * @return \OpenAPI\Server\Model\Workplace[]
     */
    public function workplacesGet(
            ?bool $includeDisabled,
    ):
        array
    ;


    /**
     * Operation workplacesIdDelete
     *
     * Delete workplace
     * @param string $id
     * @return \OpenAPI\Server\Model\NoContent204
     */
    public function workplacesIdDelete(
            string $id,
    ):
        \OpenAPI\Server\Model\NoContent204
    ;


    /**
     * Operation workplacesIdPut
     *
     * Update workplace
     * @param string $id
     * @param \OpenAPI\Server\Model\Workplace $workplace
     * @return \OpenAPI\Server\Model\NoContent200
     */
    public function workplacesIdPut(
            string $id,
            \OpenAPI\Server\Model\Workplace $workplace,
    ):
        \OpenAPI\Server\Model\NoContent200
    ;


    /**
     * Operation workplacesPost
     *
     * Create workplace
     * @param \OpenAPI\Server\Model\Workplace $workplace
     * @return \OpenAPI\Server\Model\NoContent201
     */
    public function workplacesPost(
            \OpenAPI\Server\Model\Workplace $workplace,
    ):
        \OpenAPI\Server\Model\NoContent201
    ;

}
