/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Area } from '../../models/area';
import { AreaWrite } from '../../models/area-write';

export interface CreateArea$Params {
      body: AreaWrite
}

export function createArea(http: HttpClient, rootUrl: string, params: CreateArea$Params, context?: HttpContext): Observable<StrictHttpResponse<Area>> {
  const rb = new RequestBuilder(rootUrl, createArea.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Area>;
    })
  );
}

createArea.PATH = '/areas';
