/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Area } from '../../models/area';

export interface GetArea$Params {
  id: string;
}

export function getArea(http: HttpClient, rootUrl: string, params: GetArea$Params, context?: HttpContext): Observable<StrictHttpResponse<Area>> {
  const rb = new RequestBuilder(rootUrl, getArea.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Area>;
    })
  );
}

getArea.PATH = '/areas/{id}';
