/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Area } from '../../models/area';
import { SortOrderWrite } from '../../models/sort-order-write';

export interface ReorderAreas$Params {
  body: SortOrderWrite;
}

export function reorderAreas(
  http: HttpClient,
  rootUrl: string,
  params: ReorderAreas$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<Area>>> {
  const rb = new RequestBuilder(rootUrl, reorderAreas.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Area>>;
    }),
  );
}

reorderAreas.PATH = '/areas/order';
