/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Area } from '../../models/area';
import { AreaWrite } from '../../models/area-write';

export interface UpdateArea$Params {
  id: string;
      body: AreaWrite
}

export function updateArea(http: HttpClient, rootUrl: string, params: UpdateArea$Params, context?: HttpContext): Observable<StrictHttpResponse<Area>> {
  const rb = new RequestBuilder(rootUrl, updateArea.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Area>;
    })
  );
}

updateArea.PATH = '/areas/{id}';
