/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface GetCalendarFeed$Params {
  /**
   * Unknown id is a 404, so a typo in a subscription URL surfaces at once.
   */
  workplaceId?: string;

  /**
   * Comma-separated tag names. The feed then carries only bookings on workplaces
   * that hold at least one of them — the same union as tag-based blocking, not an
   * intersection. Matched case-insensitively, a leading `#` ignored. A tag no
   * workplace holds is a 404, like an unknown workplaceId, so a typo in a
   * subscription URL surfaces at once. Combined with workplaceId the two intersect.
   */
  tag?: Array<string>;
}

export function getCalendarFeed(
  http: HttpClient,
  rootUrl: string,
  params?: GetCalendarFeed$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, getCalendarFeed.PATH, 'get');
  if (params) {
    rb.query('workplaceId', params.workplaceId, {});
    rb.query('tag', params.tag, { style: 'form', explode: false });
  }

  return http.request(rb.build({ responseType: 'text', accept: 'text/calendar', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    }),
  );
}

getCalendarFeed.PATH = '/calendar.ics';
