<?php declare(strict_types=1);

/**
 * Reservation System API
 * API for managing areas, workplaces, bookings, booking series, and roles.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Http\Controllers;

use Crell\Serde\SerdeCommon;
use Illuminate\Routing\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


use OpenAPI\Server\Api\DefaultApiInterface;

class DefaultController extends Controller
{
    /**
     * Constructor
     */
    public function __construct(
        private readonly DefaultApiInterface $api,
        private readonly SerdeCommon $serde = new SerdeCommon(),
    )
    {
    }

    /**
     * Operation areasGet
     *
     * List areas.
     *
     */
    public function areasGet(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $apiResult = $this->api->areasGet();

        if (is_array($apiResult)) {
            $serialized = array_map(fn ($item) => $this->serde->serialize($item, format: 'array'), $apiResult);
            return response()->json($serialized, 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation areasIdDelete
     *
     * Delete area.
     *
     */
    public function areasIdDelete(Request $request, string $id): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'id' => $id,
                ],
                $request->all(),
            ),
            [
                'id' => [
                    'required',
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }



        $apiResult = $this->api->areasIdDelete($id);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent204) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 204);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation areasIdPut
     *
     * Update area.
     *
     */
    public function areasIdPut(Request $request, string $id): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'id' => $id,
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $area = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\Area::class);


        $apiResult = $this->api->areasIdPut($id, $area);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent200) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation areasPost
     *
     * Create area.
     *
     */
    public function areasPost(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $area = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\Area::class);


        $apiResult = $this->api->areasPost($area);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent201) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 201);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation bookingSeriesGet
     *
     * List booking series.
     *
     */
    public function bookingSeriesGet(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $apiResult = $this->api->bookingSeriesGet();

        if (is_array($apiResult)) {
            $serialized = array_map(fn ($item) => $this->serde->serialize($item, format: 'array'), $apiResult);
            return response()->json($serialized, 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation bookingSeriesIdDelete
     *
     * Delete booking series.
     *
     */
    public function bookingSeriesIdDelete(Request $request, string $id): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'id' => $id,
                ],
                $request->all(),
            ),
            [
                'id' => [
                    'required',
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }



        $apiResult = $this->api->bookingSeriesIdDelete($id);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent204) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 204);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation bookingSeriesIdPut
     *
     * Update booking series.
     *
     */
    public function bookingSeriesIdPut(Request $request, string $id): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'id' => $id,
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $bookingSeries = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\BookingSeries::class);


        $apiResult = $this->api->bookingSeriesIdPut($id, $bookingSeries);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent200) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation bookingSeriesPost
     *
     * Create booking series.
     *
     */
    public function bookingSeriesPost(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $bookingSeries = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\BookingSeries::class);


        $apiResult = $this->api->bookingSeriesPost($bookingSeries);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent201) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 201);
        }

        if ($apiResult instanceof \OpenAPI\Server\Model\BookingSeriesPost200Response) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation bookingsGet
     *
     * List bookings.
     *
     */
    public function bookingsGet(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
                'from' => [
                    'date',
                ],
                'to' => [
                    'date',
                ],
                'workplaceId' => [
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $from = $request->date('from');

        $to = $request->date('to');

        $workplaceId = $request->string('workplaceId')->value();


        $apiResult = $this->api->bookingsGet($from, $to, $workplaceId);

        if (is_array($apiResult)) {
            $serialized = array_map(fn ($item) => $this->serde->serialize($item, format: 'array'), $apiResult);
            return response()->json($serialized, 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation bookingsIdDelete
     *
     * Delete booking.
     *
     */
    public function bookingsIdDelete(Request $request, string $id): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'id' => $id,
                ],
                $request->all(),
            ),
            [
                'id' => [
                    'required',
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }



        $apiResult = $this->api->bookingsIdDelete($id);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent204) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 204);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation bookingsIdGet
     *
     * Get booking details.
     *
     */
    public function bookingsIdGet(Request $request, string $id): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'id' => $id,
                ],
                $request->all(),
            ),
            [
                'id' => [
                    'required',
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }



        $apiResult = $this->api->bookingsIdGet($id);

        if ($apiResult instanceof \OpenAPI\Server\Model\Booking) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation bookingsIdPut
     *
     * Update booking.
     *
     */
    public function bookingsIdPut(Request $request, string $id): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'id' => $id,
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $booking = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\Booking::class);


        $apiResult = $this->api->bookingsIdPut($id, $booking);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent200) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \OpenAPI\Server\Model\Error) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 409);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation bookingsPost
     *
     * Create booking.
     *
     */
    public function bookingsPost(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $booking = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\Booking::class);


        $apiResult = $this->api->bookingsPost($booking);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent201) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 201);
        }

        if ($apiResult instanceof \OpenAPI\Server\Model\Error) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 409);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation rolesGet
     *
     * List roles.
     *
     */
    public function rolesGet(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $apiResult = $this->api->rolesGet();

        if (is_array($apiResult)) {
            $serialized = array_map(fn ($item) => $this->serde->serialize($item, format: 'array'), $apiResult);
            return response()->json($serialized, 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation rolesNameDelete
     *
     * Delete role.
     *
     */
    public function rolesNameDelete(Request $request, string $name): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'name' => $name,
                ],
                $request->all(),
            ),
            [
                'name' => [
                    'required',
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }



        $apiResult = $this->api->rolesNameDelete($name);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent204) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 204);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation rolesNamePut
     *
     * Update role.
     *
     */
    public function rolesNamePut(Request $request, string $name): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'name' => $name,
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $role = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\Role::class);


        $apiResult = $this->api->rolesNamePut($name, $role);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent200) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation rolesPost
     *
     * Create role.
     *
     */
    public function rolesPost(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $role = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\Role::class);


        $apiResult = $this->api->rolesPost($role);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent201) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 201);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation workplacesGet
     *
     * List workplaces.
     *
     */
    public function workplacesGet(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
                'includeDisabled' => [
                    'boolean',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $includeDisabled = $request->boolean('includeDisabled');


        $apiResult = $this->api->workplacesGet($includeDisabled);

        if (is_array($apiResult)) {
            $serialized = array_map(fn ($item) => $this->serde->serialize($item, format: 'array'), $apiResult);
            return response()->json($serialized, 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation workplacesIdDelete
     *
     * Delete workplace.
     *
     */
    public function workplacesIdDelete(Request $request, string $id): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'id' => $id,
                ],
                $request->all(),
            ),
            [
                'id' => [
                    'required',
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }



        $apiResult = $this->api->workplacesIdDelete($id);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent204) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 204);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation workplacesIdPut
     *
     * Update workplace.
     *
     */
    public function workplacesIdPut(Request $request, string $id): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'id' => $id,
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        $workplace = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\Workplace::class);


        $apiResult = $this->api->workplacesIdPut($id, $workplace);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent200) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation workplacesPost
     *
     * Create workplace.
     *
     */
    public function workplacesPost(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $workplace = $this->serde->deserialize($request->getContent(), from: 'json', to: \OpenAPI\Server\Model\Workplace::class);


        $apiResult = $this->api->workplacesPost($workplace);

        if ($apiResult instanceof \OpenAPI\Server\Model\NoContent201) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 201);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
}
