/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FloorPlan } from '../../models/floor-plan';

export interface DeleteFloorPlan$Params {}

export function deleteFloorPlan(
  http: HttpClient,
  rootUrl: string,
  params?: DeleteFloorPlan$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<FloorPlan>> {
  const rb = new RequestBuilder(rootUrl, deleteFloorPlan.PATH, 'delete');
  if (params) {
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FloorPlan>;
    }),
  );
}

deleteFloorPlan.PATH = '/floor-plan';
