<?php declare(strict_types=1);

/**
 * Reservation System API
 * API for managing areas, workplaces, bookings, booking series, and roles.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * Area
 */
namespace OpenAPI\Server\Model;

/**
 * Area
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class Area
{
    /**
    *
    * 
    * @param string $id
    *
    * 
    * @param string $name
    *
    * 
    * @param string $color
    *
    * 
    * @param int $maxBookingDurationMinutes
    *
    * 
    * @param int $maxBookingEndOffsetDays
    *
    * 
    * @param int $sortOrder
    */

    public function __construct(
        public string $id,
        public string $name,
        public string $color,
        public int $maxBookingDurationMinutes,
        public int $maxBookingEndOffsetDays,
        public int $sortOrder,
    ) {}
}

