<?php declare(strict_types=1);

/**
 * Reservation System API
 * API for managing areas, workplaces, bookings, booking series, and roles.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * Booking
 */
namespace OpenAPI\Server\Model;

/**
 * Booking
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class Booking
{
    /**
    *
    * 
    * @param string $id
    *
    * 
    * @param string $creatorRole
    *
    * 
    * @param string $workplaceId
    *
    * Only part of the read response when the booking blocks other workplaces
    * @param string[] $blocksWorkplaceIds
    *
    * Visible only with viewBookingsDetails permission
    * @param string $name
    *
    * Visible only with viewBookingsDetails permission
    * @param string $contact
    *
    * 
    * @param \DateTime $startTime
    *
    * 
    * @param \DateTime $endTime
    *
    * 
    * @param null | string $bookingSeriesId
    */

    public function __construct(
        public string $id,
        public string $creatorRole,
        public string $workplaceId,
        public array $blocksWorkplaceIds,
        public string $name,
        public string $contact,
        public \DateTime $startTime,
        public \DateTime $endTime,
        public ?string $bookingSeriesId = null,
    ) {}
}

