<?php declare(strict_types=1);

/**
 * Reservation System API
 * API for managing areas, workplaces, bookings, booking series, and roles.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * Role
 */
namespace OpenAPI\Server\Model;

/**
 * Role
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class Role
{
    /**
    *
    * 
    * @param string $name
    *
    * 
    * @param string $passwordHash
    *
    * 
    * @param \OpenAPI\Server\Model\RolePermissions $permissions
    */

    public function __construct(
        public string $name,
        public string $passwordHash,
        public \OpenAPI\Server\Model\RolePermissions $permissions,
    ) {}
}

