<?php declare(strict_types=1);

/**
 * Reservation System API
 * API for managing areas, workplaces, bookings, booking series, and roles.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * RolePermissions
 */
namespace OpenAPI\Server\Model;

/**
 * RolePermissions
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class RolePermissions
{
    /**
    *
    * View bookings without name and contact details
    * @param bool $viewBookings
    *
    * View bookings with name and contact details
    * @param bool $viewBookingsDetails
    *
    * Create bookings
    * @param bool $createBookings
    *
    * Ignore time-based booking restrictions when creating or managing bookings
    * @param bool $noTimeRestrictions
    *
    * Manage bookings
    * @param bool $manageBookings
    *
    * Manage workplaces
    * @param bool $manageWorkplaces
    *
    * Manage areas
    * @param bool $manageAreas
    *
    * Manage user roles
    * @param bool $manageRoles
    */

    public function __construct(
        public bool $viewBookings,
        public bool $viewBookingsDetails,
        public bool $createBookings,
        public bool $noTimeRestrictions,
        public bool $manageBookings,
        public bool $manageWorkplaces,
        public bool $manageAreas,
        public bool $manageRoles,
    ) {}
}

