<?php declare(strict_types=1);

/**
 * Reservation System API
 * API for managing areas, workplaces, bookings, booking series, and roles.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * WorkplaceStatus
 */
namespace OpenAPI\Server\Model;

/**
 * WorkplaceStatus
 */
enum WorkplaceStatus: string
{
        case OK = 'OK';
        case DEFECT = 'DEFECT';
        case DISABLED = 'DISABLED';
}
