<?php declare(strict_types=1);

/**
 * Reservation System API
 * API for managing areas, workplaces, bookings, booking series, and roles.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * Workplace
 */
namespace OpenAPI\Server\Model;

/**
 * Workplace
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class Workplace
{
    /**
    *
    * 
    * @param string $id
    *
    * 
    * @param string $name
    *
    * 
    * @param string $description
    *
    * 
    * @param \OpenAPI\Server\Model\WorkplaceStatus $status
    *
    * 
    * @param string $location
    *
    * 
    * @param string $areaId
    *
    * 
    * @param string $wikiUrl
    *
    * 
    * @param null | int $maxBookingDurationMinutes
    *
    * 
    * @param string[] $blocksWorkplaceIds
    *
    * 
    * @param string[] $blocksWorkplacesWithTag
    *
    * 
    * @param string[] $tags
    *
    * 
    * @param int $sortOrder
    */

    public function __construct(
        public string $id,
        public string $name,
        public string $description,
        public \OpenAPI\Server\Model\WorkplaceStatus $status,
        public string $location,
        public string $areaId,
        public string $wikiUrl,
        public array $blocksWorkplaceIds,
        public array $blocksWorkplacesWithTag,
        public array $tags,
        public int $sortOrder,
        public ?int $maxBookingDurationMinutes = null,
    ) {}
}

